version: '3.8'
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=system1
      - MYSQL_DATABASE=spiral_db
      - MYSQL_USER=spiral
      - MYSQL_PASSWORD=system1
    ports:
      - "3306:3306"
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3     
    networks:
      - app_network 

  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network 
            
  server:
    build: ./server
    restart: always   
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis      
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30   
    networks:
      - app_network 
      
  worker:
    build: ./worker
    restart: always
    depends_on:
      - mysql
      - redis
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app_network 
      
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
      - worker
    networks:
      - app_network 
      
networks:
  app_network:
    driver: bridge      
      
volumes:
  mysql_data:
  redis_data:      
        