CREATE DATABASE IF NOT EXISTS spiral_db;

CREATE USER 'spiral'@'%' IDENTIFIED BY 'system1!';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `projectone`.* TO 'projectoneuser'@'%';

FLUSH PRIVILEGES;